version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf   # Mount custom nginx.conf
    networks:
      - my_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
